### ISSUE TITLE
Support for CollectiveAllReduceStrategy strategy

### ISSUE THREAD

**Issue by gogasca** [linkedin/TonY#227]
DistributionStrategy API is an easy way to distribute your training across multiple devices/machines. Goal is to allow users to use existing models and training code with minimal changes to enable distributed training. Moreover, we've designed the API in such a way that it works with both eager and graph execution

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distribute/README.md
This feature request is to be able to explore support to run Multi-worker training using CollectiveAllReduceStrategy and TonY.

**Comment by erwa** [comment]
HI @gogasca ,

I think these distribution strategies should already be supported in TonY because this is decided at the TensorFlow level. TonY just starts the worker and ps tasks but then it's up to the user's TF code to decide which DistributionStrategy to use. Internally, we have AI folks who have tried all 3 (MirroredStrategy, CollectiveAllReduceStrategy, and ParameterServerStrategy) on Tony>

**Comment by gogasca** [comment]
That is great, If time permits I will try to add a sample so we can highlight this in the Next talk.
Thanks

**Comment by erwa** [comment]
Going to close this issue for now; please reopen another issue specifically for adding a CollectiveAllReduceStrategy if you plan to do so.
