### ISSUE TITLE
host token expires when tony asks for many containers 

### ISSUE THREAD

**Issue by oliverhu** [linkedin/TonY#379]
```19/09/27 03:24:57 INFO impl.AMRMClientImpl: Received new token for : host:8041
19/09/27 03:24:57 INFO tony.ApplicationMaster: Launching a task in container, containerId = containerid, containerNode = host:8041, resourceRequest = <memory:20480, vCores:1>, priority = 0
19/09/27 03:34:57 INFO tony.ApplicationMaster: Launching a task in container, containerId = containerid, containerNode = host:8041, resourceRequest = <memory:20480, vCores:1>, priority = 0
19/09/27 03:35:18 INFO impl.ContainerManagementProtocolProxy: Opening proxy : host:8041
19/09/27 03:35:18 ERROR tony.ApplicationMaster: Failed to start container containerid
```
AMRMClient gets token for a host once, if the RM failed to allocate the container in that host within 10 minutes, the token would expire. Need a way to renew or recover

**Comment by hungj** [comment]
Issue is that AM does not launch containers fast enough after receiving allocation.

The token timers start when AM heartbeats and pulls its latest allocations. If many containers are requested, it will receive these allocations in a batch.

AM then uses a single thread to launch containers on these allocations:
`    @Override
    public void onContainersAllocated(List<Container> containers) {
      LOG.info("Allocated: " + containers.size() + " containers.");
      for (Container container : containers) {
        LOG.info("Launching a task in container"
            + ", containerId = " + container.getId()
            + ", containerNode = " + container.getNodeId().getHost() + ":" + container.getNodeId().getPort()
            + ", resourceRequest = " + container.getResource()
            + ", priority = " + container.getPriority());
        new ContainerLauncher(container).run();
      }
    }`

We found there's slowness between the above log line and this log line:
`LOG.info("Setting Container [" + container.getId() + "] for task [" + task.getId() + "]..");`

The slowness is likely coming from Utils.addResources, which is called for each configured resource to be localized. Utils.addResource calls a listStatus here:
```
        if (localizableResource.isDirectory()) {
          Path dirpath = localizableResource.getSourceFilePath();
          FileStatus[] ls = fs.listStatus(dirpath);
          for (FileStatus fileStatus : ls) {
            // We only add first level files.
            if (fileStatus.isDirectory()) {
              continue;
            }
            addResource(fileStatus.getPath().toString(), resourcesMap, fs);
          }
        }
```
The list status could be slow (on the order of seconds). Then if there's a large number of containers, the total latency for the last container to be launched is (numContainers - 1) * (numDirectoryResources) * (listStatus latency). Hence the issue appears when there's a lot of containers requested, each of which configures a directory to be localized (which causes the listStatus code path to be invoked).

Some potential fixes:

- Multi-thread the container launches
- Cache the result of listStatus (since resources to be localized should be the same per-taskType)

The first option seems easiest to implement, and should fix the issue. Second option can be implemented on top of this.
